FROM ubuntu:20.04

LABEL maintainer="noreika.eimantas@gmail.com"
LABEL version="0.1"
LABEL description="This is simple docker image what releases dart package from open api swagger config"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y nodejs git npm default-jre && \
    apt clean

RUN npm install
RUN npm install -g @openapitools/openapi-generator-cli